### ISSUE TITLE
Westmeath only returns appts for athlone

### ISSUE THREAD

**Issue by canuckjacq** [williamoconnorme/hse-pcr-test-appointment-alerts#2]
Opening in case someone knows why off the top of their heads. Happy to have a closer look at it myself when I'm allowed to have my laptop open again on Wednesday. ![image](https://user-images.githubusercontent.com/11161530/147913917-181216b1-e061-497a-90a9-b7e4bc716fec.png)

The HSE site returns 3 sites, two of which are actually in Westmeath 

![image](https://user-images.githubusercontent.com/11161530/147914014-b9c2a024-23d3-4699-bb6d-02cd01a60493.jpeg)

**Comment by baztastic** [comment]
I'm not the maintainer, but the telegram bot only posts when there's an available slot, so maybe the other centres didn't have any slots to post about?

**Comment by canuckjacq** [comment]
I might have to check at midnight!

**Comment by williamoconnorme** [comment]
@baztastic is probably right here. I've seen some counties return different centres for other counties

**Comment by canuckjacq** [comment]
Yeah, I think this is right - I've seen people saying they aren't seeing slots at all in Mullingar when they are checking. Ugh, the state of this place. 

Closing :) sorry for the noise
